# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-30 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsinfo',
            old_name='gkuncun',
            new_name='gkucun',
        ),
    ]
